---
- name: Gather Dell Switch Info (Generic CLI)
  hosts: all
  gather_facts: no
  collections:
    - ansible.netcommon

  tasks:
    - name: Run "show version"
      ansible.netcommon.cli_command:
        command: show version
      register: version_info

    - name: Print output
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "{{ version_info.stdout }}"
