---
- name: Gather Dell Switch Info
  hosts: all
  gather_facts: no

  tasks:
    - name: Run "show version"
      ansible.netcommon.cli_command:
        command: show version
      register: version_info

    - name: Run "show system uptime"
      ansible.netcommon.cli_command:
        command: show system uptime
      register: uptime_info

    - name: Display device info
      debug:
        msg:
          - "Version Info: {{ version_info.stdout }}"
          - "Uptime Info: {{ uptime_info.stdout }}"
