---
- name: Get Dell Switch Version Info
  hosts: dell_switches
  gather_facts: no
  tasks:
    - name: Run "show version"
      raw: show version
      register: version_output

    - name: Display output
      debug:
        var: version_output.stdout_lines
