---
# AutoSage Enhanced Version of: Windows-system-check.yml
# ===================================================
#
# This playbook includes AutoSage integration for AI-powered analysis
# of your Windows system monitoring tasks.
#
# Original playbook: Windows-system-check.yml
# Source: https://github.com/nadzzdan/Constella
# Enhanced with AutoSage: {{ ansible_date_time.iso8601 }}

- name: AutoSage Enhanced - Windows System Check
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: yes
  become: no
  
  vars:
    autosage_api_url: "{{ autosage_api_url | default('http://10.50.0.33:8007/api/report/') }}"
    autosage_debug: "{{ autosage_debug | default('false') }}"
    original_playbook: "Windows-system-check.yml"
    original_playbook_name: "Windows System Check"
    
  pre_tasks:
    - name: Display AutoSage integration information
      debug:
        msg: |
          🚀 AutoSage Enhanced Windows System Check
          =========================================
          
          Original Playbook: {{ original_playbook }}
          Source Repository: https://github.com/nadzzdan/Constella
          AutoSage API: {{ autosage_api_url }}
          Target Hosts: {{ ansible_play_hosts }}
          Integration Mode: Enhanced
          
          AutoSage will automatically analyze Windows system data
          and provide AI-powered insights for Windows optimization.

  tasks:
    # Original Windows system check tasks
    - name: Get Windows system information
      win_shell: |
        Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, TotalPhysicalMemory, CsProcessors
      register: windows_system_info

    - name: Get Windows CPU information
      win_shell: |
        Get-Counter '\Processor(_Total)\% Processor Time' | Select-Object -ExpandProperty CounterSamples | Select-Object CookedValue
        Get-WmiObject -Class Win32_Processor | Select-Object Name, NumberOfCores, NumberOfLogicalProcessors
      register: windows_cpu_info

    - name: Get Windows memory information
      win_shell: |
        Get-Counter '\Memory\Available MBytes' | Select-Object -ExpandProperty CounterSamples | Select-Object CookedValue
        Get-WmiObject -Class Win32_OperatingSystem | Select-Object TotalVisibleMemorySize, FreePhysicalMemory
      register: windows_memory_info

    - name: Get Windows disk information
      win_shell: |
        Get-WmiObject -Class Win32_LogicalDisk | Select-Object DeviceID, Size, FreeSpace, @{Name="FreePercent";Expression={[math]::Round(($_.FreeSpace/$_.Size)*100,2)}}
      register: windows_disk_info

    - name: Get Windows services status
      win_shell: |
        Get-Service | Where-Object {$_.Status -eq "Running"} | Select-Object Name, DisplayName, Status | Sort-Object Name
      register: windows_services_status

    # AutoSage Enhanced: Additional Windows metrics
    - name: Get enhanced Windows metrics
      win_shell: |
        Write-Host "=== ENHANCED WINDOWS METRICS ==="
        Write-Host "System Uptime: $((Get-Date) - (Get-CimInstance Win32_OperatingSystem).LastBootUpTime)"
        Write-Host "Active Processes: $(Get-Process | Measure-Object | Select-Object -ExpandProperty Count)"
        Write-Host "Network Connections: $(Get-NetTCPConnection | Measure-Object | Select-Object -ExpandProperty Count)"
        Write-Host "Event Log Errors (Last 24h): $(Get-EventLog -LogName System -EntryType Error -After (Get-Date).AddDays(-1) | Measure-Object | Select-Object -ExpandProperty Count)"
        Write-Host "Windows Updates Status: $(Get-HotFix | Sort-Object -Property InstalledOn -Descending | Select-Object -First 1 | Select-Object -ExpandProperty HotFixID)"
      register: enhanced_windows_metrics

    # AutoSage Enhanced: Send Windows data to AutoSage for AI analysis
    - name: Send Windows data to AutoSage for AI analysis
      uri:
        url: "{{ autosage_api_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body: |
          {
            "task": "AutoSage Enhanced Windows System Check",
            "host": "{{ inventory_hostname }}",
            "status": "ok",
            "result": {
              "changed": false,
              "msg": "Windows system check completed with AutoSage AI analysis",
              "test_mode": false,
              "autosage_enhanced": true,
              "original_playbook": "{{ original_playbook }}",
              "source_repository": "https://github.com/nadzzdan/Constella",
              "windows_metrics": {
                "windows_system_info": "{{ windows_system_info.stdout }}",
                "windows_cpu_info": "{{ windows_cpu_info.stdout }}",
                "windows_memory_info": "{{ windows_memory_info.stdout }}",
                "windows_disk_info": "{{ windows_disk_info.stdout }}",
                "windows_services_status": "{{ windows_services_status.stdout }}",
                "enhanced_windows_metrics": "{{ enhanced_windows_metrics.stdout }}"
              },
              "performance_data": {
                "hostname": "{{ inventory_hostname }}",
                "os": "{{ ansible_os_name | default('Windows') }}",
                "architecture": "{{ ansible_architecture | default('unknown') }}",
                "timestamp": "{{ ansible_date_time.iso8601 }}",
                "playbook_source": "github.com/nadzzdan/Constella",
                "windows_monitoring": true
              },
              "stdout": "Windows system check completed with AutoSage AI analysis",
              "stderr": "",
              "rc": 0
            }
          }
        timeout: 30
        status_code: [200, 201, 400, 500]
      register: autosage_report
      ignore_errors: yes

    - name: Display Complete Windows Report with AutoSage Integration
      debug:
        msg: |
          
          ========================================
          AUTOSAGE ENHANCED WINDOWS SYSTEM CHECK
          ========================================
          Host: {{ inventory_hostname }}
          Timestamp: {{ ansible_date_time.iso8601 }}
          AutoSage API: {{ autosage_api_url }}
          Source: https://github.com/nadzzdan/Constella
          
          === WINDOWS SYSTEM INFORMATION ===
          {{ windows_system_info.stdout }}
          
          === CPU INFORMATION ===
          {{ windows_cpu_info.stdout }}
          
          === MEMORY INFORMATION ===
          {{ windows_memory_info.stdout }}
          
          === DISK INFORMATION ===
          {{ windows_disk_info.stdout }}
          
          === SERVICES STATUS ===
          {{ windows_services_status.stdout }}
          
          === ENHANCED WINDOWS METRICS ===
          {{ enhanced_windows_metrics.stdout }}
          
          ========================================
          AUTOSAGE AI ANALYSIS
          ========================================
          {% if autosage_report.status in [200, 201] %}
          ✅ AutoSage AI analysis completed successfully
          Report ID: {{ autosage_report.json.report_id | default('N/A') }}
          AI Insights: {{ autosage_report.json.ai_analysis | default('Available in AutoSage dashboard') }}
          {% else %}
          ⚠️  AutoSage AI analysis status: {{ autosage_report.status }}
          Note: Windows check completed, but AI analysis may not be available
          {% endif %}
          
          ========================================
          ✅ AutoSage Enhanced Windows Check Complete!
          ========================================
          
          View detailed AI analysis at: http://10.50.0.33:8007

  post_tasks:
    - name: Generate AutoSage integration summary
      debug:
        msg: |
          =========================================
          AUTOSAGE INTEGRATION SUMMARY
          =========================================
          Playbook: {{ original_playbook }}
          Source Repository: https://github.com/nadzzdan/Constella
          Hosts: {{ ansible_play_hosts }}
          Tasks Executed: {{ ansible_play_hosts | length }}
          AutoSage API: {{ autosage_api_url }}
          Timestamp: {{ ansible_date_time.iso8601 }}
          
          ✅ AutoSage integration enabled
          📊 Windows metrics sent to AutoSage for AI analysis
          🤖 AI-powered Windows insights generated
          📈 Enhanced Windows monitoring active
          🌐 View results at: http://10.50.0.33:8007
          
          =========================================
