---
- name: Dell VM Host Health Check
  hosts: vmhosts
  gather_facts: no
  
  tasks:
    - name: Get System Overview
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getsysinfo'
      register: system_info
      delegate_to: localhost
      
    - name: Get Firmware Versions
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getversion'
      register: firmware_version
      delegate_to: localhost
      
    - name: Get System LED Status
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getled'
      register: led_status
      delegate_to: localhost
      
    - name: Get System Event Log
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getsel -o'
      register: event_log
      delegate_to: localhost
      
    - name: Get iDRAC Network Configuration
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getniccfg'
      register: nic_config
      delegate_to: localhost
      
    - name: Extract Key Information
      set_fact:
        system_model: "{{ system_info.stdout | regex_search('System Model\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
        host_name: "{{ system_info.stdout | regex_search('Host Name\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
        bios_version: "{{ system_info.stdout | regex_search('System BIOS Version\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
        power_status: "{{ system_info.stdout | regex_search('Power Status\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
        led_state: "{{ led_status.stdout | regex_search('LED State :\\t(.+)', '\\1') | first | default('Unknown') }}"
        idrac_version: "{{ firmware_version.stdout | regex_search('iDRAC Version\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
    
    # Display Results - Table Format
    - name: "VM Host Health Check Report"
      debug:
        msg:
          - ""
          - "╔════════════════════════════════════════════════════════════════╗"
          - "║           VM HOST HEALTH CHECK REPORT                          ║"
          - "╠════════════════════════════════════════════════════════════════╣"
          - "║ Host Name       : {{ host_name | default('Unknown') | ljust(45) }}║"
          - "║ iDRAC IP        : {{ ansible_host | ljust(45) }}║"
          - "║ Model           : {{ system_model | default('Unknown') | ljust(45) }}║"
          - "║ BIOS Version    : {{ bios_version | default('Unknown') | ljust(45) }}║"
          - "║ iDRAC Version   : {{ idrac_version | default('Unknown') | ljust(45) }}║"
          - "║ Power Status    : {{ power_status | default('Unknown') | ljust(45) }}║"
          - "╠════════════════════════════════════════════════════════════════╣"
          - "║ LED Status      : {{ led_state | default('Unknown') | ljust(45) }}║"
          - "║ Health          : {% if led_state == 'Not-Blinking' %}✓ HEALTHY{{ ' ' | ljust(38) }}{% else %}⚠️  CHECK HARDWARE{{ ' ' | ljust(31) }}{% endif %}║"
          - "╚════════════════════════════════════════════════════════════════╝"
          - ""
    
    - name: "System Events (Latest 10)"
      debug:
        msg:
          - ""
          - "━━━━━━━━━━━━━━━━ SYSTEM EVENTS ━━━━━━━━━━━━━━━━"
          - "{{ event_log.stdout_lines[:10] | join('\n') }}"
          - "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          - ""
