---
- name: Dell VM Host Health Check
  hosts: vmhosts
  gather_facts: no
  
  tasks:
    - name: Get System Overview
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getsysinfo'
      register: system_info
      delegate_to: localhost
      
    - name: Get Firmware Versions
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getversion'
      register: firmware_version
      delegate_to: localhost
      
    - name: Get System LED Status
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getled'
      register: led_status
      delegate_to: localhost
      
    - name: Get System Event Log
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getsel -o'
      register: event_log
      delegate_to: localhost
      
    - name: Get iDRAC Network Configuration
      shell: |
        sshpass -p '{{ ansible_password }}' ssh {{ ansible_ssh_common_args }} {{ ansible_user }}@{{ ansible_host }} 'racadm getniccfg'
      register: nic_config
      delegate_to: localhost
      
    - name: Extract Key Information
      set_fact:
        system_model: "{{ system_info.stdout | regex_search('System Model\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
        host_name: "{{ system_info.stdout | regex_search('Host Name\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
        bios_version: "{{ system_info.stdout | regex_search('System BIOS Version\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
        power_status: "{{ system_info.stdout | regex_search('Power Status\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
        led_state: "{{ led_status.stdout | regex_search('LED State :\\t(.+)', '\\1') | first | default('Unknown') }}"
        idrac_version: "{{ firmware_version.stdout | regex_search('iDRAC Version\\s+=\\s+(.+)', '\\1') | first | default('Unknown') }}"
    
    # Display Results - Table Format
    - name: "VM Host Health Check Results"
      debug:
        msg:
          - ""
          - "=========================================="
          - "VM HOST HEALTH CHECK REPORT"
          - "=========================================="
          - ""
          - "Host Name        : {{ host_name }}"
          - "iDRAC IP         : {{ ansible_host }}"
          - "Model            : {{ system_model }}"
          - "BIOS Version     : {{ bios_version }}"
          - "iDRAC Version    : {{ idrac_version }}"
          - "Power Status     : {{ power_status }}"
          - ""
          - "LED Status       : {{ led_state }}"
          - "Health Status    : {% if led_state == 'Not-Blinking' %}✓ SYSTEM HEALTHY{% else %}⚠️ CHECK HARDWARE{% endif %}"
          - ""
          - "=========================================="
    
    - name: "Latest System Events"
      debug:
        var: event_log.stdout_lines
