---
- name: Dell Switch - Display Cleaned Interface Output Only
  hosts: dell_switches
  gather_facts: no
  #vars:
  #  switch_ip: "10.0.0.5"
  #  username: "janestrada"
  #  password: "Love2eat"

  tasks:
    - name: SSH and run 'show interfaces' manually
      ansible.builtin.expect:
        command: ssh -o StrictHostKeyChecking=no {{ username }}@{{ switch_ip }}
        responses:
          (?i)password: "{{ password }}"
          (?i)#: "show interfaces\nexit"
        timeout: 30
      register: interfaces_result
      ignore_errors: yes

    - name: Clean and display interface result
      debug:
        msg: |
          === Cleaned Dell Switch Interface Output ===
          {{ interfaces_result.stdout
             | replace('\r', '')
             | regex_replace('--More--.*', '')
             | regex_replace('\n{2,}', '\n') }}
