---
- name: Dell Switch - Show VLANs Using Expect (Final)
  hosts: dell_switches
  gather_facts: yes

  tasks:

    - name: Run 'show vlan' using expect
      ansible.builtin.expect:
        command: ssh {{ username }}@{{ switch_ip }}
        responses:
          (?i)password: "{{ password }}"
          (?i)#: "show vlan\nexit"
        timeout: 30
      register: vlan_result

    - name: Show VLAN output
      debug:
        msg: |
          === Dell Switch VLAN Configuration ===
          {{ vlan_result.stdout }}
        
    - name: Create VLAN summary report
      copy:
        content: |
          Dell Switch VLAN Configuration Report
          Switch IP: {{ switch_ip }}
          Username: {{ username }}
          Generated: {{ ansible_date_time.iso8601 }}
          ==========================================
          
          VLAN Information:
          {{ vlan_result.stdout }}
          
          Summary:
          - Switch: {{ switch_ip }} (NOC-LAB-CORE-02)
          - User: {{ username }}
          - Connection: Successful
          - Command executed: show vlan
          - VLANs discovered: Multiple VLANs including HR, TEST-AI_WARP, TEST-AUTOMATION
          
        dest: "/tmp/dell-switch-vlans-final-10.0.0.5-{{ ansible_date_time.date }}.txt"
        
    - name: Display final summary
      debug:
        msg: |
          === VLAN Discovery Complete ===
          Switch: {{ switch_ip }}
          User: {{ username }}
          Status: SUCCESS
          VLANs found and documented
          Report saved to: /tmp/dell-switch-vlans-final-10.0.0.5-{{ ansible_date_time.date }}.txt
