---
- name: Basic Dell Switch Management - 10.0.0.5
  hosts: dell_switch_10_0_0_5
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_user: janestrada
    ansible_password: Love2eat
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: generic
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  tasks:
    - name: Execute basic show commands
      raw: |
        show version
        show interface status
        show vlan
        show running-config | include hostname
      register: basic_info
      
    - name: Display switch basic information
      debug:
        var: basic_info.stdout_lines
        
    - name: Test connectivity with ping
      raw: ping 8.8.8.8 count 3
      register: ping_test
      ignore_errors: yes
      
    - name: Save basic switch information
      copy:
        content: |
          Dell Switch Basic Report - 10.0.0.5
          Generated: {{ ansible_date_time.iso8601 }}
          Credentials: janestrada / Love2eat
          ==========================================
          
          Basic Switch Information:
          {{ basic_info.stdout }}
          
          Connectivity Test:
          {{ ping_test.stdout | default('Ping test failed or not supported') }}
          
        dest: "/tmp/dell-switch-basic-10.0.0.5-{{ ansible_date_time.date }}.txt"
      delegate_to: localhost
