---
- name: Comprehensive Dell Access Switch Management - 10.0.0.5
  hosts: dell_switch_10_0_0_5
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_user: janestrada
    ansible_password: Love2eat
    ansible_connection: ansible.netcommon.network_cli
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_command_timeout: 30
    
  tasks:
    - name: Test basic connectivity
      ansible.netcommon.net_ping:
        dest: "{{ ansible_host }}"
      delegate_to: localhost
      
    - name: Try to determine Dell OS type
      raw: show version
      register: version_output
      ignore_errors: yes
      
    - name: Set network OS based on version output
      set_fact:
        detected_os: >-
          {% if 'Dell EMC Networking OS10' in version_output.stdout %}
          dellos10
          {% elif 'Dell Networking OS' in version_output.stdout %}
          dellos9
          {% elif 'PowerConnect' in version_output.stdout %}
          dellos6
          {% else %}
          generic
          {% endif %}
      when: version_output.stdout is defined
      
    - name: Display detected OS
      debug:
        msg: "Detected Dell OS: {{ detected_os | default('unknown') }}"
        
    - name: Gather system information
      raw: |
        show version
        show system
        show interfaces status
        show vlan
        show mac address-table
        show spanning-tree
      register: system_info
      ignore_errors: yes
      
    - name: Get running configuration
      raw: show running-config
      register: running_config
      ignore_errors: yes
      
    - name: Display system information summary
      debug:
        msg: |
          === Dell Switch Information Summary ===
          Switch IP: {{ ansible_host }}
          Detected OS: {{ detected_os | default('unknown') }}
          Connection Status: {{ 'Success' if system_info.rc == 0 else 'Failed' }}
          
    - name: Save comprehensive switch report
      copy:
        content: |
          Dell Access Switch Comprehensive Report
          Switch IP: 10.0.0.5
          Username: janestrada
          Generated: {{ ansible_date_time.iso8601 }}
          =============================================
          
          Detection Results:
          - Detected OS: {{ detected_os | default('Could not determine') }}
          - Connection Status: {{ 'Successful' if system_info.rc == 0 else 'Failed' }}
          
          System Information:
          {{ system_info.stdout }}
          
          {% if running_config.stdout is defined %}
          Running Configuration:
          {{ running_config.stdout }}
          {% endif %}
          
          Raw Command Outputs:
          - Version Check: {{ version_output.stdout | default('Failed to retrieve') }}
          
        dest: "/tmp/dell-switch-comprehensive-10.0.0.5-{{ ansible_date_time.date }}.txt"
      delegate_to: localhost
      
    - name: Create switch management summary
      debug:
        msg: |
          === Dell Switch Management Summary ===
          Target: 10.0.0.5
          User: janestrada
          Status: {{ 'Connected' if system_info.rc == 0 else 'Connection Failed' }}
          OS Type: {{ detected_os | default('Unknown') }}
          Report saved to: /tmp/dell-switch-comprehensive-10.0.0.5-{{ ansible_date_time.date }}.txt
