---
- name: Dell Switch - Show Interfaces Only
  hosts: dell_switches
  gather_facts: no
  #vars:
  #  switch_ip: "10.0.0.5"
  #  username: "janestrada"
  #  password: "Love2eat"

  tasks:
    - name: Run 'show interfaces' using expect
      ansible.builtin.expect:
        command: ssh -o StrictHostKeyChecking=no {{ username }}@{{ switch_ip }}
        responses:
          (?i)password: "{{ password }}"
          (?i)#: "show interfaces\nexit"
        timeout: 30
      register: interfaces_result
      ignore_errors: yes

    - name: Clean detailed interfaces output
      set_fact:
        interfaces_result_cleaned: >-
          {{ interfaces_result.stdout
             | replace('\r', '')
             | regex_replace('--More--.*', '')
             | regex_replace('\n{2,}', '\n') }}

    - name: Show Detailed Interface Information
      debug:
        msg: |
          === Detailed Interface Information ===
          {{ interfaces_result_cleaned }}

    - name: Create Interface summary report
      copy:
        content: |
          Dell Switch Interface Report
          Switch IP: {{ switch_ip }}
          Username: {{ username }}
          Generated: {{ ansible_date_time.iso8601 }}
          ============================================
          
          Detailed Interface Information:
          {{ interfaces_result_cleaned }}
          
          Summary:
          - Switch: {{ switch_ip }} (NOC-LAB-CORE-02)
          - User: {{ username }}
          - Command executed: show interfaces

        dest: "/tmp/dell-switch-interfaces-{{ switch_ip }}-{{ ansible_date_time.date }}.txt"

    - name: Display final summary
      debug:
        msg: |
          === Interface Discovery Complete ===
          Switch: {{ switch_ip }}
          User: {{ username }}
          Status: SUCCESS
          Output saved to: /tmp/dell-switch-interfaces-{{ switch_ip }}-{{ ansible_date_time.date }}.txt
