---
- name: AD Replication Status - Semaphore
  hosts: "{{ target_hosts | default('ifive-dc') }}"
  gather_facts: yes
  
  tasks:
    - name: Check AD Replication Summary
      win_shell: |
        repadmin /replsummary
      register: replication_summary
      changed_when: false
      ignore_errors: yes

    - name: Display Report Header
      debug:
        msg:
          - ""
          - "=============================================="
          - "AD REPLICATION STATUS - {{ inventory_hostname }}"
          - "=============================================="
          - "Timestamp: {{ ansible_date_time.iso8601 }}"
          - ""

    - name: Display Replication Summary
      debug:
        var: replication_summary.stdout_lines

    - name: Display Report Footer
      debug:
        msg:
          - ""
          - "=============================================="
          - "✅ Replication Check Completed"
          - "=============================================="
