---
- name: AD Replication Status - Semaphore
  hosts: "{{ target_hosts | default('ifive-dc') }}"
  gather_facts: yes
  
  tasks:
    - name: Check AD Replication Summary
      win_shell: |
        Write-Host "Replication Status for: $env:COMPUTERNAME"
        Write-Host "=============================================="
        Write-Host ""
        repadmin /replsummary * /bysrc /bydest
      register: replication_summary
      changed_when: false
      ignore_errors: yes
      run_once: true

    - name: Display Replication Summary
      debug:
        msg: "{{ replication_summary.stdout_lines }}"
      run_once: true
