---
- name: Linux System Resources Check - Semaphore
  hosts: "{{ target_hosts | default('linux_vms') }}"
  gather_facts: yes
  become: no
  
  tasks:
    - name: Get CPU Information
      shell: |
        echo "CPU Model: $(grep 'model name' /proc/cpuinfo | head -1 | cut -d: -f2 | xargs)"
        echo "CPU Cores: $(nproc)"
        echo "CPU Usage: $(top -bn1 | grep 'Cpu(s)' | awk '{print $2}' | cut -d'%' -f1)%"
        echo "Load Average: $(uptime | awk -F'load average:' '{print $2}' | xargs)"
      register: cpu_info
      changed_when: false

    - name: Get Memory Information
      shell: |
        echo "Total RAM: $(free -h | grep Mem | awk '{print $2}')"
        echo "Used RAM: $(free -h | grep Mem | awk '{print $3}')"
        echo "Free RAM: $(free -h | grep Mem | awk '{print $4}')"
        echo "RAM Usage: $(free | grep Mem | awk '{printf \"%.1f%%\", $3/$2 * 100.0}')"
      register: memory_info
      changed_when: false

    - name: Get Storage Information
      shell: |
        echo "Disk Usage:"
        df -h | grep -E '^/dev/' | head -5
      register: storage_info
      changed_when: false

    - name: Get System Uptime
      shell: |
        echo "System Uptime: $(uptime -p)"
        echo "Last Boot: $(who -b | awk '{print $3, $4}')"
      register: uptime_info
      changed_when: false

    - name: Display Complete System Report
      debug:
        msg: |
          
          ========================================
          SYSTEM RESOURCES - {{ inventory_hostname }}
          ========================================
          Timestamp: {{ ansible_date_time.iso8601 }}
          
          {{ cpu_info.stdout }}
          
          {{ memory_info.stdout }}
          
          {{ storage_info.stdout }}
          
          {{ uptime_info.stdout }}
          
          ========================================
          ✅ System check completed successfully!
          ========================================
